{% set name = "pytest-excel" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-excel-{{ version }}.tar.gz
  sha256: ed472758b37302d867970e7ffa01d16fb37e7d6bdcdbe9bc21fbc61900a94597

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pytest >=3.6
    - openpyxl

test:
  imports:
    - pytest_excel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ssrikanta/pytest-excel
  summary: pytest plugin for generating excel reports
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
