{% set name = "pytest-excel" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d7f54d24c25a2f6052305809d4e0d224434fbe7a139bd162e3326cba7105e72a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pytest >=3.6
    - pandas

test:
  imports:
    - pytest_excel
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ssrikanta/pytest-excel
  summary: pytest plugin for generating excel reports
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
